In [2]:
import pandas as pd
dataFrame = pd.read_csv('world.csv')

In [3]:
allDataFrame=dataFrame.reindex(columns=['洲名','國家','日期','總確診數',
'新增確診數','七天移動平均新增確診數','總死亡數','新增死亡數','七天移動平均疫苗新增接種劑數',
'每百人接種疫苗劑數','每百人接種疫苗人數','疫情控管指數','總人口數','中位數年紀',
'70歲以上人口比例','平均壽命','解除隔離數','解封指數'])

In [4]:
display(allDataFrame.info())
allDataFrame['日期'] = pd.to_datetime(allDataFrame['日期'])
allDataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187885 entries, 0 to 187884
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   洲名              187885 non-null  object
 1   國家              187885 non-null  object
 2   日期              187885 non-null  object
 3   總確診數            187885 non-null  int64
 4   新增確診數           187885 non-null  int64
 5   七天移動平均新增確診數     187885 non-null  float64
 6   總死亡數            187885 non-null  int64
 7   新增死亡數           187885 non-null  int64
 8   七天移動平均疫苗新增接種劑數  187885 non-null  float64
 9   每百人接種疫苗劑數       187885 non-null  float64
 10  每百人接種疫苗人數       187885 non-null  float64
 11  疫情控管指數          187885 non-null  float64
 12  總人口數            187885 non-null  int64
 13  中位數年紀           187885 non-null  float64
 14  70歲以上人口比例       187885 non-null  float64
 15  平均壽命            187885 non-null  float64
 16  解除隔離數           187885 non-null  int64
 17  解封指數            187885 non-null  float64
dtypes: float64(9), int64(6), object(3)
memory usage: 25.8+ MB

None

,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,亞洲,阿富汗,2020-02-24,5,5,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
1,亞洲,阿富汗,2020-02-25,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
2,亞洲,阿富汗,2020-02-26,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
3,亞洲,阿富汗,2020-02-27,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
4,亞洲,阿富汗,2020-02-28,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187880,非洲,辛巴威,2022-07-02,255586,0,39.571,5555,0,6190.0,79.41,41.81,0.00,15092171,19.6,1.882,61.49,0,99999.0
187881,非洲,辛巴威,2022-07-03,255586,0,33.000,5555,0,8710.0,79.55,41.86,0.00,15092171,19.6,1.882,61.49,0,99999.0
187882,非洲,辛巴威,2022-07-04,255726,140,49.000,5558,3,10797.0,79.67,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187883,非洲,辛巴威,2022-07-05,255755,29,53.143,5558,0,10821.0,79.68,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187884,非洲,辛巴威,2022-07-06,255805,50,40.714,5560,2,0.0,0.00,0.00,0.00,15092171,19.6,1.882,61.49,0,99999.0

In [10]:
display(allDataFrame)
allDataFrame[allDataFrame['洲名'] == '亞洲']

,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,亞洲,阿富汗,2020-02-24,5,5,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
1,亞洲,阿富汗,2020-02-25,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
2,亞洲,阿富汗,2020-02-26,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
3,亞洲,阿富汗,2020-02-27,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
4,亞洲,阿富汗,2020-02-28,5,0,0.000,0,0,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187880,非洲,辛巴威,2022-07-02,255586,0,39.571,5555,0,6190.0,79.41,41.81,0.00,15092171,19.6,1.882,61.49,0,99999.0
187881,非洲,辛巴威,2022-07-03,255586,0,33.000,5555,0,8710.0,79.55,41.86,0.00,15092171,19.6,1.882,61.49,0,99999.0
187882,非洲,辛巴威,2022-07-04,255726,140,49.000,5558,3,10797.0,79.67,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187883,非洲,辛巴威,2022-07-05,255755,29,53.143,5558,0,10821.0,79.68,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187884,非洲,辛巴威,2022-07-06,255805,50,40.714,5560,2,0.0,0.00,0.00,0.00,15092171,19.6,1.882,61.49,0,99999.0

,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,亞洲,阿富汗,2020-02-24,5,5,0.000,0,0,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
1,亞洲,阿富汗,2020-02-25,5,0,0.000,0,0,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
2,亞洲,阿富汗,2020-02-26,5,0,0.000,0,0,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
3,亞洲,阿富汗,2020-02-27,5,0,0.000,0,0,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
4,亞洲,阿富汗,2020-02-28,5,0,0.000,0,0,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186200,亞洲,葉門,2022-07-02,11824,0,0.000,2149,0,0.0,0.0,0.0,0.00,30490639,20.3,1.583,66.12,0,99999.0
186201,亞洲,葉門,2022-07-03,11824,0,0.000,2149,0,0.0,0.0,0.0,0.00,30490639,20.3,1.583,66.12,0,99999.0
186202,亞洲,葉門,2022-07-04,11832,8,1.143,2149,0,0.0,0.0,0.0,0.00,30490639,20.3,1.583,66.12,0,99999.0
186203,亞洲,葉門,2022-07-05,11832,0,1.143,2149,0,0.0,0.0,0.0,0.00,30490639,20.3,1.583,66.12,0,99999.0
186204,亞洲,葉門,2022-07-06,11832,0,1.143,2149,0,0.0,0.0,0.0,0.00,30490639,20.3,1.583,66.12,0,99999.0

In [13]:
display(allDataFrame.query('國家 == "台灣"'))
display(allDataFrame.query('國家 == "日本"'))

Empty DataFrame
Columns: [洲名, 國家, 日期, 總確診數, 新增確診數, 七天移動平均新增確診數, 總死亡數, 新增死亡數, 七天移動平均疫苗新增接種劑數, 每百人接種疫苗劑數, 每百人接種疫苗人數, 疫情控管指數, 總人口數, 中位數年紀, 70歲以上人口比例, 平均壽命, 解除隔離數, 解封指數]
Index: []

,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
85626,亞洲,日本,2020-01-22,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.0
85627,亞洲,日本,2020-01-23,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.0
85628,亞洲,日本,2020-01-24,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.0
85629,亞洲,日本,2020-01-25,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.0
85630,亞洲,日本,2020-01-26,4,2,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,1,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86518,亞洲,日本,2022-07-02,9364954,24875,19682.000,31309,11,145101.0,226.63,82.31,39.81,126050796,48.2,18.493,84.63,0,99999.0
86519,亞洲,日本,2022-07-03,9388222,23268,20976.571,31314,5,147030.0,226.69,82.31,39.81,126050796,48.2,18.493,84.63,0,99999.0
86520,亞洲,日本,2022-07-04,9405007,16785,22009.571,31328,14,158310.0,226.84,82.32,39.81,126050796,48.2,18.493,84.63,0,99999.0
86521,亞洲,日本,2022-07-05,9441171,36164,24409.429,31348,20,166711.0,226.99,82.32,39.81,126050796,48.2,18.493,84.63,0,99999.0
86522,亞洲,日本,2022-07-06,9486965,45794,27619.429,31360,12,170354.0,227.11,82.32,0.00,126050796,48.2,18.493,84.63,0,99999.0

In [15]:
Taiwan_Japan = allDataFrame.query('國家=="台灣" or 國家=="日本"')
Taiwan_Japan

,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
85626,亞洲,日本,2020-01-22,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.00
85627,亞洲,日本,2020-01-23,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.00
85628,亞洲,日本,2020-01-24,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.00
85629,亞洲,日本,2020-01-25,2,0,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,0,99999.00
85630,亞洲,日本,2020-01-26,4,2,0.000,0,0,0.0,0.00,0.00,2.78,126050796,48.2,18.493,84.63,1,99999.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164884,亞洲,台灣,2022-07-02,3837856,34807,37736.143,6868,96,85345.0,0.00,0.00,0.00,23855008,42.2,8.353,80.46,14835,258.17
164885,亞洲,台灣,2022-07-03,3870528,32672,36740.429,6956,88,83512.0,243.72,88.80,0.00,23855008,42.2,8.353,80.46,14835,260.37
164886,亞洲,台灣,2022-07-04,3893643,23115,35960.286,7025,69,80397.0,244.04,88.81,0.00,23855008,42.2,8.353,80.46,14835,261.94
164887,亞洲,台灣,2022-07-05,3929627,35984,34755.571,7128,103,79776.0,244.41,88.82,0.00,23855008,42.2,8.353,80.46,14835,264.37
164888,亞洲,台灣,2022-07-06,3964188,34561,33689.286,7223,95,75670.0,244.76,88.83,0.00,23855008,42.2,8.353,80.46,14835,266.71